repository: tomjoht/documentation-theme-jekyll
output: web
topnav_title: Jekyll Documentation Theme
site_title: Jekyll theme for documentation
company_name: Copyright 2021 Google LLC
github_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
google_analytics: UA-66296557-1
host: 127.0.0.1
port: 4000
exclude:
  - .idea/
  - .gitignore
  - vendor
feedback_subject_line: Jekyll documentation theme
feedback_email: tomjoht@gmail.com
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
collections:
  tooltips:
    output: false
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  - scope:
      path: ''
      type: tooltips
    values:
      layout: page
      search: true
      tooltip: true
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
sidebars:
  - home_sidebar
  - mydoc_sidebar
  - product1_sidebar
  - product2_sidebar
  - other
description: >-
  Intended as a documentation theme based on Jekyll for technical writers
  documenting software and other technical products, this theme has all the
  elements you would need to handle multiple products with both multi-level
  sidebar navigation, tags, and other documentation features.
github:
  - metadata
baseurl: ''
url: ''
